# Generated by Django 5.1.7 on 2025-07-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userbio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=1500, null=True)),
                ('college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('college_year', models.CharField(blank=True, max_length=4, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usebio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
