# Generated by Django 5.1.7 on 2025-07-18 22:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbio',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
