// src/app/layout.jsx

import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer'; // ✅ Only once
import { AuthProvider }  from '../Authcontext/Authcontext';
import Head from 'next/head';



export const metadata = {
  title: 'Campusconnects',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico', // ✅ Favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <AuthProvider>
        <Header />
        {children}
        <Footer />
        </AuthProvider>
      </body>
      
<Head>
        <title>CampusConnects | Connect and Build</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="google-site-verification" content="KPKs3OsCjZAtRcjQUgJrBbd7GUgwR8VBQquPK2PlHiw" />
        <meta
          name="description"
          content="CampusConnects empowers students to connect, collaborate, and build meaningful communities through shared interests, events, and opportunities."
        />
        <meta
          name="keywords"
          content="CampusConnects, college networking, student community, campus events, student collaboration, connect with peers, university network"
        />
        <meta name="author" content="CampusConnects Team" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />

        {/* Open Graph Meta Tags */}
        <meta property="og:title" content="CampusConnects | Connect and Build" />
        <meta
          property="og:description"
          content="Join a thriving campus network where students connect, share, and grow together. Discover events, clubs, and collaborations."
        />
        <meta property="og:image" content="https://www.campusconnects.in/og-image.jpg" />
        <meta property="og:url" content="https://www.campusconnects.in" />
        <meta property="og:type" content="website" />

        {/* Twitter Card Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="CampusConnects | Connect and Build" />
        <meta
          name="twitter:description"
          content="Empowering students to connect and collaborate through campus networks and events."
        />
        <meta name="twitter:image" content="https://www.campusconnects.in/og-image.jpg" />
      </Head>
      
    </html>
  );
}