// src/app/layout.jsx

import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer'; // ✅ Only once
import { AuthProvider }  from './Auth/Authcontext/page';


export const metadata = {
  title: 'Campusconnects',
  description: 'Generated by Next.js',
  icons: {
    icon: '/image/favicon.ico', // ✅ Favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <Header />
        {children}
        <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
